apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: hello
    spec:
      containers:
      - name: hello
        image: payalsasmal/hello:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: hello

---
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
    - port: 5000
      targetPort: 5000
  
  type: LoadBalancer
