apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: hello-pod
spec:
  containers:
    - name: myjenkinsdocker
      image: payalsasmal/1strepository:tagVersion
      ports:
        - containerPort: 8888
