apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app : hello-service
spec:
  selector:
    app: hello-pod
    tier: hello-pod
  ports:
   - port: 5000
     targetPort: 5000
  type: LoadBalancer

